# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shop

  target 'ShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'ReachabilitySwift'
pod 'SDWebImage', '~> 5.0'
pod 'TextFieldEffects'
pod 'Cosmos'
pod 'JJFloatingActionButton'

end
